version: "3"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: demo
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  gorm_demo:
    build: .
    restart: always
    ports:
      - "8090:8090"
    links:
      - postgres:postgreshost
